[package]
name = "microcheby"
version = "0.1.0"
edition = "2021"
license = "MIT"
categories = []
keywords=[]
exclude=[]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["std"]
std = []